---
Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: MyKey


# After creating, run these commands
# aws ec2 describe-key-pairs --filters Name=key-name,Values=MyKey --query KeyPairs[*].KeyPairId --output text
# aws ssm get-parameter --name /ec2/keypair/key-070e83a6a1bf7239c --with-decryption --query Parameter.Value --output text > MyKey.pem